config/routes.rb
Rails.application.routes.draw do
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


  root 'welcome#index'

  resources :meals
  resources :users, except: [:index, :destroy] do
    resources :meals, only: [:index, :show]
  end
  
  get "/signup" => 'user#new', as 'signup'
  get 'login' => 'sessions#new', as: 'login'
  post 'login' => 'sessions#create'
  delete "/logout" => 'sessions#destroy'

  get 'dashboard' => 'users#dashboard', as: 'dashboard'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/meal.rb
class Meal < ApplicationRecord
  belongs_to :user

  validates :name, format: { with: /\A[a-zA-Z0-9_ -]+\z/, message: "cannot contain symbols" }
  validates :calories, numericality: { only_integer: true }

  def self.by_user(user_id)
    where(user: user_id)
  end

  def self.from_today
    where("created_at >=?", Time.zone.today.beginning_of_day)
  end

  def self.old_meals
    where("created_at <?", Time.zone.today.beginning_of_day)
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :meals

  has_secure_password

  ## validation for account creation
  validates :username, presence: true, uniqueness: true, length: { minimum: 2}, format: { with: /\A[a-zA-Z0-9_-]+\z/, message: "cannot contain blank spaces or symbols" }
  validates :password_confirmation, presence: true, on: :create
  validates :password, presence: true, length: { in: 6..20 }, confirmation: true, unless: ->(u){ u.password.blank? }

  ## validation for user information
  validates :age, presence: true, numericality: { only_integer: true}, unless: ->(u){ u.age.blank? }
  validates :height, presence: true, numericality: { only_integer: true}, unless: ->(u){ u.height.blank? }
  validates :weight, presence: true, numericality: { only_integer: true}, unless: ->(u){ u.weight.blank? }
end

app/models/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    @user = User.new
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :logged_in?
  helper_method :current_user

  private

  def current_user
    # return unless session[:user_id]
    User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def authenticate
    if !logged_in? || current_user.nil?
      redirect_to login_path
    end
  end

  # checks if user is logged in and available
  def authorize?
    !current_user.nil? && !!logged_in?
  end
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController

  def index
    # gives us the list of all users so we can filter
    @users = User.all

    # filters the @meals based on user choice
    if !params[:user].blank?
      @meals = Meal.by_user(params[:user])
    elsif !params[:date].blank?
      if params[:date] == "Today"
        @meals = Meal.from_today
      else
        @meals = Meal.old_meals
      end
    else
      # if no filters are applied, show all meals
      @meals = Meal.all
    end

  end


  



end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    redirect_to dashboard_path if authorize?
  end

  def create
    user = User.find_by(username: params[:username])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:success] = "Login Success!"
      redirect_to dashboard_path
    else
      flash[:error] = "WTF BRO? TRY AGAIN"
      redirect_to login_path
    end
  end

  def destroy

  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  include UsersHelper
  include MealsHelper

  before_action :find_user, only: [:index, :show, :edit, :update, :destroy, :index]

  def index

  end

  def show
    
  end

  def new
    @user = User.new
  end

  def edit

  end

  def create
    @user = User.new(user_params(:username, :password, :password_confirmation))
    if @user.save
      # to log in
      session[:user_id] = @user.id
      flash[:notice] = "Yo #{@user.username}!"
      redirect_to dashboard_path
    else
      flash[:alert] = "WTF BRO"
      render "new"
    end
  end

  def update

  end

  def destroy

  end

  def dashboard
    authenticate
    @user = current_user
    @current_calories = get_current_calories(@user)
  end

  private

  def user_params(*args)
    params.require(:user).permit(*args)
  end

  def find_user
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def navbar
    if logged_in?
      render 'layouts/logged_in_navbar'
    else
      render 'layouts/logged_out_navbar'
    end
  end
end

app/helpers/meals_helper.rb
module MealsHelper

  def grab_meals_from_today(meals)
    today_meals = []
    meals.each do |meal|
      if meal.created_at.strftime("%D") == Date.today.strftime("%D")
        today_meals << meal
      end
    end
    today_meals
  end    

end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def get_current_calories(user)
    cals = 0
    meals = grab_meals_from_today(user.meals)
    meals.each do |meal|
      cals += meal.calories
    end
    cals
  end

end

app/views/layouts/_logged_in_navbar.html.erb
<%= button_to "Logout", "/logout", method: :delete %>

app/views/layouts/_logged_out_navbar.html.erb
<%= link_to "Log In", login_path %>

<%= link_to "Sign Up", signup_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CalorieTracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <header>
    <%= navbar %>
  </header>

    <h1>Welcome to blah blahhhhh Calorie blahhh</h1>
   
    <% flash.each do |k,v| %>
      <div class=<%= k %>><%= v %></div>
    <% end %>


    <%= yield %>
  </body>
</html>

app/views/meals/index.html.erb
<h1>Check out all the meals</h1>

<div>
  <h3>Filter the meals:</h3>
  <%= form_tag("/meals", method: "get") do %>
    <%= select_tag "user", options_from_collection_for_select(@users, "id", "username"), include_blank: "Users" %>
    <%= select_tag "date", options_for_select(["Today", "Old Meals"]), include_blank: "Date" %>
    <%= submit_tag "Filter" %>
  <% end %>
</div>

<% @meals.each do |meal| %>
  <div>
    <h2><%= meal.name %></h2>
    <h3>by: <%= link_to meal.user.username, user_path(meal.user) %></h3>
    <p><%= meal.calories %> Calories</p>
    <p>Notes: <%= meal.notes %></p>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>

  <%= f.label :username %> <br>
  <%= f.text_field :username %> <br>

  <%= f.label :password %> <br>
  <%= f.password_field :password %> <br>

  <%= f.label :password_confirmation %> <br>
  <%= f.password_field :password_confirmation %> <br>

  <%= f.submit "Create Account" %>

<% end %>

app/views/users/dashboard.html.erb
<h3>Hey <%= @user.username.titlecase %>!</h3>

<%= flash[:success] %>

<!--If tdee is filled up, display info-->
<% if !@user.tdee.nil? %>
    
    <p>These are your current stats.</p>

    <table>
      <tr>
        <th>Current Weight (lbs)</th>
        <th>Goal</th>
        <th>Current (kcal)</th>
        <th>Recommended (kcal)</th>
        <th>BMR (kcal)</th>
        <th>TDEE (kcal)</th>
      
      </tr>
      <tr>
        <td><%= @user.weight %></td>
        <td><%= @user.goal %></td>
        <td><%= @current_calories %></td>
        <td> placeholder </td>
        <td><%= @user.bmr %></td>
        <td><%= @user.tdee %></td>
       
      </tr>
  </table> 

<% end %>

app/views/users/new.html.erb
<h3>Register here</h3>

<% if @user.errors.any? %>
  <div class="error-box">
    <h3><%= pluralize(@user.errors.count, "error") %> prohibited your account from being created:</h3>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div><br>
<% end %>

<%= render "form" %>

<br> <br>

<%= link_to 'Back', root_path %>

app/views/users/show.html.erb
<h3><%= @user.username %></h3>
<% @user.meals.each.with_index do |meal, index| %>
  <p>Meal #<%= index + 1 %> <br> 
  <p><%= link_to meal.name, meal_path(meal) %></p>
  <p><%= meal.calories %> Calories</p>
  <p>Notes: <%= meal.notes %></p>
<% end %>

app/views/welcome/index.html.erb
<h2>Welcome ya momos</h2>

<%= link_to "Register", new_user_path(@user) %>